GET http://localhost:3000/api/players 
content-type: application/json

###
POST http://localhost:3000/api/players
content-type: application/json

    {
        "firstname": "Emma",
        "lastname": "Bro",
        "side": "Backhand",
        "gender": "Female",
        "level": "Professional"
     }

###
PUT http://localhost:3000/api/players/472ea409-419c-400c-8e97-8f33e5858733 
content-type: application/json

    {
        "firstname": "Erik",
        "lastname": "Johansson",
        "side": "Forehand",
        "gender": "Male",
        "level": "Advanced"
    }

###

DELETE http://localhost:3000/api/players/54a4e80e-539b-4248-99d9-c5a4eed94c7a
content-type: application/json

###

GET http://localhost:3000/api/players/3f8cca98-dd2a-4875-abe9-03b8119090b1
content-type: application/json

###



