GET http://localhost:3000/api/players 
content-type: application/json


###
POST http://localhost:3000/api/players
content-type: application/json

    {
        "firstname": "Emma",
        "lastname": "Bro",
        "side": "Backhand",
        "gender": "Female",
        "level": "Professional"
     }

###
PUT http://localhost:3000/api/players/8253bfbe-bae6-42df-a8b4-eb6f0b202c95 
content-type: application/json

    {
        "firstname": "Erik",
        "lastname": "Johansson",
        "side": "Forehand",
        "gender": "Male",
        "level": "Advanced"
    }

###

DELETE http://localhost:3000/api/players/bae21a8d-1487-42e1-bd80-99d728846807
content-type: application/json

###

GET http://localhost:3000/api/players/8253bfbe-bae6-42df-a8b4-eb6f0b202c95
content-type: application/json

###



